defmodule Nimrag.Api.Profile do
  use Nimrag.Api.Data

  schematic_struct do
    field(:id, integer())
    field(:profile_id, integer())
    field(:garmin_guid, String.t(), json: "garminGUID", nullable: true)
    field(:display_name, String.t())
    field(:full_name, String.t())
    field(:user_name, String.t())
    field(:profile_image_url_large, String.t(), nullable: true)
    field(:profile_image_url_medium, String.t(), nullable: true)
    field(:profile_image_url_small, String.t(), nullable: true)
    field(:location, String.t(), nullable: true)
    field(:facebook_url, String.t(), nullable: true)
    field(:twitter_url, String.t(), nullable: true)
    field(:personal_website, String.t(), nullable: true)
    field(:motivation, integer(), nullable: true)
    field(:bio, String.t(), nullable: true)
    field(:primary_activity, String.t(), nullable: true)
    field(:favorite_activity_types, list(String.t()))
    field(:running_training_speed, float())
    field(:cycling_training_speed, float())
    field(:favorite_cycling_activity_types, list(String.t()))
    field(:cycling_classification, String.t(), nullable: true)
    field(:cycling_max_avg_power, float())
    field(:swimming_training_speed, float())
    field(:profile_visibility, String.t())
    field(:activity_start_visibility, String.t())
    field(:activity_map_visibility, String.t())
    field(:course_visibility, String.t())
    field(:activity_heart_rate_visibility, String.t())
    field(:activity_power_visibility, String.t())
    field(:badge_visibility, String.t())
    field(:show_age, boolean())
    field(:show_weight, boolean())
    field(:show_height, boolean())
    field(:show_weight_class, boolean())
    field(:show_age_range, boolean())
    field(:show_gender, boolean())
    field(:show_activity_class, boolean())
    field(:show_vo_2_max, boolean(), json: "showVO2Max")
    field(:show_personal_records, boolean())
    field(:show_last_12_months, boolean())
    field(:show_lifetime_totals, boolean())
    field(:show_upcoming_events, boolean())
    field(:show_recent_favorites, boolean())
    field(:show_recent_device, boolean())
    field(:show_recent_gear, boolean())
    field(:show_badges, boolean())
    field(:other_activity, String.t(), nullable: true)
    field(:other_primary_activity, String.t(), nullable: true)
    field(:other_motivation, String.t(), nullable: true)
    field(:user_roles, list(String.t()))
    field(:name_approved, boolean())
    field(:user_profile_full_name, String.t())
    field(:make_golf_scorecards_private, boolean())
    field(:allow_golf_live_scoring, boolean())
    field(:allow_golf_scoring_by_connections, boolean())
    field(:user_level, integer())
    field(:user_point, integer())
    field(:level_update_date, String.t())
    field(:level_is_viewed, boolean())
    field(:level_point_threshold, integer())
    field(:user_point_offset, integer())
    field(:user_pro, boolean())
  end
end
